$(document).ready(function() {
    $('#example').DataTable( {
        "paging":   true,
        "ordering": false,
        "info":     false,
        "bFilter": false,
        "lengthChange": false
    } );
} );
